# Generated by Django 5.2.3 on 2025-07-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwarehouseitem',
            name='stock_level',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='stock_level',
        ),
    ]
