# Generated by Django 5.2.3 on 2025-06-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='stock_level',
            field=models.PositiveIntegerField(default=True, verbose_name='تعداد محصول موجود در انبار'),
        ),
    ]
