# Generated by Django 5.2.3 on 2025-07-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_historicalwarehouseitem_stock_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price',
        ),
    ]
