# Generated by Django 5.2.3 on 2025-07-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_historicalproduct_sell_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalWarehouseItem',
        ),
        migrations.DeleteModel(
            name='WarehouseItem',
        ),
    ]
