# Generated by Django 5.2.3 on 2025-06-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='transaction.invoice', verbose_name='فاکتور'),
        ),
    ]
