# Generated by Django 5.2.3 on 2025-07-02 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_historicalinvoice_invoice_type_invoice_invoice_type'),
        ('user', '0002_customer_historicalcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.customer', verbose_name='مشتری'),
        ),
    ]
