# Generated by Django 5.2.3 on 2025-07-02 13:34

import django.db.models.deletion
import django_jalali.db.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_historicalinvoice_customer_and_more'),
        ('user', '0004_alter_customer_role_alter_historicalcustomer_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('credit_type', models.CharField(choices=[('positive', 'مثبت'), ('negative', 'منفی')], default='positive', max_length=10, verbose_name='نوع اعتبار')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مقدار اعتبار')),
                ('reason', models.TextField(help_text='مثلا پرداخت فاکتور، هدیه، اصلاح حساب و ...', verbose_name='توضیحات')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='user.customer', verbose_name='مشتری')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.invoice', verbose_name='فاکتور')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'اعتبار',
                'verbose_name_plural': 'اعتبارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCredit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, editable=False, verbose_name='تاریخ ویرایش')),
                ('history_user_id', models.IntegerField(blank=True, null=True)),
                ('credit_type', models.CharField(choices=[('positive', 'مثبت'), ('negative', 'منفی')], default='positive', max_length=10, verbose_name='نوع اعتبار')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مقدار اعتبار')),
                ('reason', models.TextField(help_text='مثلا پرداخت فاکتور، هدیه، اصلاح حساب و ...', verbose_name='توضیحات')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.customer', verbose_name='مشتری')),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transaction.invoice', verbose_name='فاکتور')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'historical اعتبار',
                'verbose_name_plural': 'historical اعتبارات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
