# Generated by Django 5.2.3 on 2025-07-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_credit_historicalcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.invoice', verbose_name='فاکتور'),
        ),
    ]
