# Generated by Django 5.2.3 on 2025-07-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_historicalcustomer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical مشتری', 'verbose_name_plural': 'historical مشتریان'},
        ),
    ]
