# Generated by Django 5.2.3 on 2025-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('shopkeeper', 'مغازه دار'), ('visitor', 'ویزیتور'), ('Storekeeper', 'انباردار')], default='shopkeeper', max_length=15, verbose_name='نقش کاربر'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='role',
            field=models.CharField(choices=[('shopkeeper', 'مغازه دار'), ('visitor', 'ویزیتور'), ('Storekeeper', 'انباردار')], default='shopkeeper', max_length=15, verbose_name='نقش کاربر'),
        ),
    ]
